# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Rico's Blog"
weight = 1
    [en.params.sidebar]
        searchPage = "/search/"